spring:
  application:
    name: PersonManager
  banner:
    location: JPD.txt
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PSSWRD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      generate-ddl: true
      hibernate:
        "[format_sql]": true
        "[show_sql]": true
        "[default_schema]": pctaller
server:
  port: ${SERVER_PORT} 
logging:
  level:
   "[org.springframework.web]": TRACE
# This will only be useful if this service is within the reach of an eureka server
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_PORT}/eureka
